export const techIcons = {
  mongodb: { url: 'https://cdn.simpleicons.org/mongodb' },
  nodejs: { url: 'https://cdn.simpleicons.org/nodedotjs' },
  react: { url: 'https://cdn.simpleicons.org/react' },
  php: { url: 'https://cdn.simpleicons.org/php' },
  laravel: { url: 'https://cdn.simpleicons.org/laravel' },
  python: { url: 'https://www.svgrepo.com/show/452091/python.svg' },
  javascript: { url: 'https://cdn.simpleicons.org/javascript' },
  css: { url: 'https://cdn-icons-png.flaticon.com/512/5968/5968242.png' },
  html: { url: 'https://cdn.simpleicons.org/html5' },
  tailwindcss: { url: 'https://cdn.simpleicons.org/tailwindcss' },
  bootstrap: { url: 'https://cdn.simpleicons.org/bootstrap' },
  mysql: { url: 'https://cdn.simpleicons.org/mysql' },
  tailwindcss: { url: 'https://cdn.simpleicons.org/tailwindcss' },
  express: { url: 'https://cdn.simpleicons.org/express' },
  typescript: { url: 'https://cdn.simpleicons.org/typescript' },
};
