export const techIcons = {
  mongodb: { url: 'https://cdn.simpleicons.org/mongodb', name: 'MongoDB' },
  nodejs: { url: 'https://cdn.simpleicons.org/nodedotjs', name: 'Node.js' },
  react: { url: 'https://cdn.simpleicons.org/react', name: 'React' },
  php: { url: 'https://cdn.simpleicons.org/php', name: 'PHP' },
  laravel: { url: 'https://cdn.simpleicons.org/laravel', name: 'Laravel' },
  python: { url: 'https://www.svgrepo.com/show/452091/python.svg', name: 'Python' },
  javascript: { url: 'https://cdn.simpleicons.org/javascript', name: 'JavaScript' },
  css: { url: 'https://cdn-icons-png.flaticon.com/512/5968/5968242.png', name: 'CSS' },
  html: { url: 'https://cdn.simpleicons.org/html5', name: 'HTML' },
  tailwindcss: { url: 'https://cdn.simpleicons.org/tailwindcss', name: 'Tailwind CSS' },
  bootstrap: { url: 'https://cdn.simpleicons.org/bootstrap', name: 'Bootstrap' },
  mysql: { url: 'https://pngimg.com/d/mysql_PNG23.png', name: 'MySQL' },
  tailwindcss: { url: 'https://cdn.simpleicons.org/tailwindcss', name: 'Tailwind CSS' },
  express: { url: 'https://cdn.simpleicons.org/express', name: 'Express' },
  typescript: { url: 'https://cdn.simpleicons.org/typescript', name: 'TypeScript' },
  firebase: { url: 'https://pnghdpro.com/wp-content/themes/pnghdpro/download/social-media-and-brands/firebase-studio-logo-icon.png', name: 'Firebase' },
  googleaistudio: { url: 'https://upload.wikimedia.org/wikipedia/commons/b/b5/Google_ai_studio_logo.png', name: 'Google AI Studio' },
};
